# build stage
FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server ./cmd/api/main.go

# run stage
FROM alpine:3.13

WORKDIR /app

COPY --from=builder /app/server .

EXPOSE $PORT

CMD ["/app/server"]
